# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Han-Hung Lee
title: B.S. in Undergraduate Program of Electrical Engineering and Computer Science
email: rexleeppp@gmail.com
website: https://hanhung.github.io/

# Social links
# twitter_username: facespics
github_username:  hanhung
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I am Han-Hung Lee and I'm a student that recently graduated from NTHU with a B.S. degree in the Undergraduate Program of Electrical Engineering and Computer Science. A few of my research interests include <mark>3D Point Cloud/Voxel</mark>, <mark>Reinforcement Learning</mark> and <mark>Games</mark>.

# projects_title: Publications
# projects_content: | # this will include new lines to allow paragraphs
#   - Han-Hung Lee, Da-Gin Wu, and Hwann-Tzong Chen, “Stylizing Audio Reactive Visuals,” NeurIPS 2019 Workshopon Machine Learning for Creativity and Design, December 14th, 2019, Vancouver, Canada.
#   - Pin-Hao Huang*,Han-Hung Lee*, Hwann-Tzong Chen and Tyng-Luh Liu.  “Text-guided Graph Neural Networksfor Referring 3D Instance Segmentation.” AAAI (2021).

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Resume Template
more_content: | # this will include new lines to allow paragraphs
  The template used to make this page can be found here: [link](https://github.com/sproogen/modern-resume-theme)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
